aws_account_id                 ="154320630104"
region                         = "us-east-1"
profile                        = "default"
environment                    = "dev1"
project                        = "seahorse"
register_component_lambda_name = "RegisterComponentLambda"
get_components_lambda_name = "GetRegisteredComponents"
dynamo_admin_table_name = "FSBL_COMPONENTS"
idp-name = "Globallink"
user-pool-client-redirect-urls=["http://localhost:3000","http://localhost:3375/components/seaHorseAuthentication/SeaHorseAuthenticationCallback.html","https://s3.amazonaws.com/dev.seahorse.finsemble/components/seaHorseAuthentication/SeaHorseAuthenticationCallback.html"]
user-pool-client-logout-urls=["http://localhost:3000","http://localhost:3375/components/seaHorseAuthentication/SeaHorseAuthentication.html","https://s3.amazonaws.com/dev.seahorse.finsemble/components/seaHorseAuthentication/SeaHorseAuthentication.html"]