aws_account_id="276164198880"
region                         = "us-east-1"
profile                        = "276164198880_GL-ReleaseEngg"
environment                    = "dev"
project                        = "seahorse"
register_component_lambda_name = "RegisterComponentLambda"
dynamo_admin_table_name = "FSBL_CONFIG"