region                         = "us-east-1"
profile                        = "276164198880_GL-ReleaseEngg"
environment                    = "dev"
project                        = "seahorse"
register-component-lambda-name = "RegisterComponentLambda"